pipeline {
  agent any
  tools {
    nodejs 'node-18'
}
  stages {
    stage('checkout') {
      steps {
         git branch: 'main', url: 'https://github.com/Himabindu222/Super-mario.git'
        }
     }
     stage('Install Dependencies') {
            steps {
              dir('super-mario-mimic') {
                sh 'npm install'
              }
            }
        }
    stage('Test') {
            steps {
                sh 'npm test || echo "No tests defined"'
            }
        }

    stage('Build') {
            steps {
              dir('super-mario-mimic') {
                sh 'npm run build'
              }
            }
        }
    stage('docker build') {
            steps {
                sh 'docker build -t himabindu156/super-mario:v1 .'
            }
        } 
    stage('docker deploy') {
            steps {
                sh 'docker run -d -p 8070:80 --name supermario himabindu156/super-mario:v1'
            }
        }    
    }
}
