pipeline {
  agent any
  tools {
    nodejs 'node-18'
}
  environment {
      DOCKER_IMAGE = "himabindu156/super-mario"
      DOCKER_TAG =  "v1"
   }
  stages {
    stage('checkout') {
      steps {
         git branch: 'main', url: 'https://github.com/Himabindu222/Super-mario.git'
        }
     }
     stage('Install Dependencies') {
            steps {
              dir('super-mario-mimic') {
                sh 'npm install'
              }
            }
        }
    stage('Test') {
            steps {
                sh 'npm test || echo "No tests defined"'
            }
        }

    stage('Build') {
            steps {
              dir('super-mario-mimic') {
                sh 'npm run build'
              }
            }
        }
    stage('docker build') {
            steps {
                dir('super-mario-mimic') {
                sh 'docker build -t $DOCKER_IMAGE:$DOCKER_TAG .'
                }
            }
        } 
    stage('docker login') {
        steps{
            withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-cred',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                } 
        }
    }
    stage('Push Image') {
            steps {
                sh 'docker push $DOCKER_IMAGE:$DOCKER_TAG'
            }
        }
    stage('docker deploy') {
            steps {
                sh 'docker run -d -p 8070:80 --name supermario $DOCKER_IMAGE:$DOCKER_TAG'
            }
        }    
    }
}
